SV32-DV Plan Execution - core-v-verif
10x-Engineers/core-v-verif pull request #11
Opened 2023-08-25 14:25 UTC by Ammarkhan561

## [Test for In-Valid Permission of PTE](https://github.com/10x-Engineers/core-v-verif/commit/7e486adaf21f458111f45f680bb50344508d4fc9)

I've added a new test case to cover scenarios involving invalid permissions of Page Table Entries (PTEs). When a PTE does not have valid permission (pte.V=0), attempting to access it will result in a page fault exception of the corresponding access type.

The test cases are specifically designed for situations when satp.mode=sv32 and the PTE has (r,w,x) PMP (Physical Memory Protection) permissions. The following tests have been implemented and executed in both supervisor and user privilege modes for both level0 and level1 PTEs:

1. Set PTE.V = 0 and test read access.
2. Set PTE.V = 0 and test write access.
3. Set PTE.V = 0 and test execute access.

Please review the changes and let me know if any further adjustments or additions are needed. Your feedback is highly appreciated!

#### Files and their purpose:

|   **`File Name`**   	|  **`Mode`**  	| **`Level`** 	| **`Testing For`** 	| 
|:------------------------:|:------------------:|:-----------------:|:-------------------------:|
| **[vm_invalid_pte_01.S](https://github.com/10x-Engineers/core-v-verif/commit/7e486adaf21f458111f45f680bb50344508d4fc9#diff-d3713a17bd2553f3fc0678d9004afb3e3141636ff89cd3ae255bb7575baa3ce9)** 	|   Supervisor /User	|     1     	|        RWX Access  	|
| **[vm_invalid_pte_02.S](https://github.com/10x-Engineers/core-v-verif/commit/7e486adaf21f458111f45f680bb50344508d4fc9#diff-7b121747f1e1ca5cca878160c1867084f76fc825b044179a77384ea4ed338fef)** 	|   Supervisor /User	|     0    	|    	 RWX Access     	|   

**YAML File** 
[testlist_riscv-mmu-cv32a60x.yaml](https://github.com/10x-Engineers/core-v-verif/commit/7e486adaf21f458111f45f680bb50344508d4fc9#diff-99dc7616197d245b3e0c2162050f3ef81205f9f36517f52b6acb4338b2690d9e) 

**MACRO File**
[macros.h](https://github.com/10x-Engineers/core-v-verif/commit/7e486adaf21f458111f45f680bb50344508d4fc9#diff-179db93f75765bbd7fa4d3eba488f2dc57255b406e55d9cd1d741f79e068058b)

To run the tests on core-v-verif use this command `./cva6/regress/dv-riscv-arch-test.sh`

2023-08-25 14:29 UTC, fatimasaleem commented on cva6/regress/dv-riscv-arch-test.sh
> +  DV_TARGET=cv32a60x
Do not upstream these changes, these changes are only supposed to be done for local testing.

2023-08-25 14:31 UTC, fatimasaleem commented on cva6/tests/custom/vm_invalid_pte01.S
> +#   🌟 RWX Access of Level1 PTE in User and Supervisor mode when valid
Avoid using the stars :)

2023-08-25 14:32 UTC, fatimasaleem commented on cva6/tests/custom/vm_invalid_pte01.S
> +# 💫 Set PTE.V = 0 and test the read access.
Here as well. Please remove these stars.

2023-08-25 14:35 UTC, fatimasaleem commented on cva6/tests/testlist_riscv-mmu-cv32a60x.yaml
> +## C
remove this ##C

2023-08-25 14:42 UTC, fatimasaleem commented
Create a folder inside `custom` folder with the name of `mmu_sv32_tests` and move your tests into that folder

2023-08-25 14:44 UTC, fatimasaleem commented
rename `testlist_riscv-mmu-cv32a60x.yaml` to `testlist_riscv-arch-mmu-cv32a60x.yaml`

2023-08-25 14:46 UTC, fatimasaleem commented on cva6/tests/testlist_riscv-mmu-cv32a60x.yaml
> +- test: rv32ua-v-lrsc
tests names need to be updated according to the actual test. e.g for this test it should be something like, rv32_vm_invalid_pte_01

2023-08-27 13:56 UTC, owaisfarooq-10x requested changes

2023-08-27 13:56 UTC, owaisfarooq-10xe commented on cva6/tests/custom/macros.h
> +    bne t2, t3, not_32_bit_Instr_\label_suffix                     ;\
```suggestion
    lw t5, 0(t1)                                                   ;\
    li t2, 3                                                       ;\
    and t5, t5, t2                                                 ;\
    bne t2, t5, not_32_bit_Instr_\label_suffix                     ;\
```

2023-08-28 08:37 UTC, closed without merging